version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: locadoradb
    environment:
      POSTGRES_USER: locdbuser
      POSTGRES_PASSWORD: loc123
      POSTGRES_DB: locadoradb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
